#!/usr/bin/env bash
#
# Per-task isolated sandboxes for parallel development.
#
# `new` gives a task its own git worktree (separate directory + branch), its own
# Cargo build directory, and — by default — its own Postgres instance on a free
# port. Several tasks can therefore build AND run `pgrx` tests at the same time
# without colliding. The isolated Postgres shares the already-compiled install
# (no recompile); only a ~40 MB data dir is created per task, lazily on first use.
#
# Run pgrx commands inside a worktree via `scripts/pgx.sh` (it loads the isolated
# env). Plain `cargo build/test/bench/clippy` are isolated automatically by the
# generated .cargo/config.toml.
#
# Usage:
#   scripts/worktree.sh new <slug> [--shared-pg]   create branch task/<slug> + sandbox
#   scripts/worktree.sh ls                          list active sandboxes (+ pg ports)
#   scripts/worktree.sh rm  <slug>                  stop pg, remove worktree + caches, delete branch
#   scripts/worktree.sh gc  [--dry-run]             safety net: sweep caches orphaned outside `rm`
#
# Worktrees are created as siblings of the main clone, under
# <parent>/brindle-wt/<slug>, on the Linux-native filesystem.
# See docs/DEVELOPMENT.md § "Parallel development".

set -euo pipefail

SHARED_PGRX_HOME="$HOME/.pgrx"                 # the already-built pgrx home (install source)
PG_MAJOR=17                                    # major used for port math / start / stop

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() { sed -n '3,24p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

main_worktree() { git worktree list --porcelain | sed -n 's/^worktree //p' | head -1; }

valid_slug() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || die "invalid slug '$1' (letters, digits, . _ -)"
}

# True if a PR for branch $1 has already been merged. Squash/rebase merges rewrite the
# commits, so `git branch -d` still sees the local branch as "unmerged" — this catches
# that case. Needs `gh`; without it, returns false so the caller keeps the safe error.
branch_merged_via_pr() {
  command -v gh >/dev/null 2>&1 || return 1
  local n
  n=$(gh pr list --head "$1" --state merged --json number --jq 'length' 2>/dev/null) || return 1
  [[ "${n:-0}" -gt 0 ]]
}

# Two distinct, currently-free TCP ports.
free_port_pair() {
  python3 - <<'PY'
import socket
socks, ports = [], []
for _ in range(2):
    s = socket.socket(); s.bind(('127.0.0.1', 0)); ports.append(s.getsockname()[1]); socks.append(s)
for s in socks: s.close()
print(ports[0], ports[1])
PY
}

cmd_new() {
  local slug="" shared_pg=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --shared-pg) shared_pg=1; shift ;;
      -*) die "unknown option '$1'" ;;
      *) [[ -z "$slug" ]] && slug="$1" || die "unexpected argument '$1'"; shift ;;
    esac
  done
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"

  local branch="task/$slug" base_dir wt_dir target_dir pgrx_home
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/brindle-wt/$slug"
  target_dir="$HOME/.cargo-target/$slug"
  pgrx_home="$HOME/.pgrx-$slug"

  git show-ref --verify --quiet "refs/heads/$branch" && die "branch $branch already exists"
  [[ -e "$wt_dir" ]] && die "$wt_dir already exists"

  git fetch --quiet origin 2>/dev/null || echo "note: could not fetch origin; basing on local main"
  local base="main"
  git show-ref --verify --quiet refs/remotes/origin/main && base="origin/main"

  # `git worktree add` briefly locks refs; retry so concurrent `new` calls don't fail.
  local tries=0
  until git worktree add -b "$branch" "$wt_dir" "$base" 2>/tmp/wt-add.$$; do
    tries=$((tries + 1))
    [[ $tries -ge 5 ]] && { cat /tmp/wt-add.$$ >&2; rm -f /tmp/wt-add.$$; die "git worktree add failed"; }
    sleep 0.5
  done
  rm -f /tmp/wt-add.$$

  mkdir -p "$target_dir" "$wt_dir/.cargo"

  # Isolate plain `cargo` (build/test/bench/clippy) via the worktree's cargo config.
  cat > "$wt_dir/.cargo/config.toml" <<EOF
# Auto-generated by scripts/worktree.sh — isolates this worktree's build output.
# Not committed (.cargo/ is git-ignored); removed with the worktree.
[build]
target-dir = "$target_dir"
EOF

  # Env loaded by scripts/pgx.sh (cargo's [env] does NOT reach the cargo-pgrx
  # subcommand, and shell exports don't persist across tool calls — so the wrapper
  # re-loads this on every invocation).
  {
    echo "export CARGO_TARGET_DIR=\"$target_dir\""
    [[ $shared_pg -eq 0 ]] && echo "export PGRX_HOME=\"$pgrx_home\""
  } > "$wt_dir/.cargo/worktree-env"

  # The git-ignored local docs (orchestration board + design notes + coding standards)
  # live only in the main clone, so a fresh worktree wouldn't have them. Symlink them in
  # so the worker can read its card / CLAUDE.md, and the task board stays one shared
  # source of truth across all worktrees. (These names are git-ignored, so the symlinks
  # never get committed.)
  local main_clone; main_clone="$(main_worktree)"
  for doc in tasks design CLAUDE.md; do
    [[ -e "$main_clone/$doc" && ! -e "$wt_dir/$doc" ]] && ln -s "$main_clone/$doc" "$wt_dir/$doc"
  done

  local msg_pg="shared ($SHARED_PGRX_HOME — serialize pgrx tests)"
  if [[ $shared_pg -eq 0 ]]; then
    local p_run p_test
    read -r p_run p_test < <(free_port_pair)
    rm -rf "$pgrx_home"; mkdir -p "$pgrx_home"
    # base_port + major = run port; base_testing_port + major = test port. The
    # absolute pg_config in [configs] is copied as-is, so the compiled install is
    # shared (no recompile); only data-$major is created here, lazily on first use.
    {
      echo "base_port = $((p_run - PG_MAJOR))"
      echo "base_testing_port = $((p_test - PG_MAJOR))"
      echo
      cat "$SHARED_PGRX_HOME/config.toml"
    } > "$pgrx_home/config.toml"
    msg_pg="$pgrx_home  (run :$p_run, test :$p_test)"
  fi

  echo
  echo "created sandbox:"
  echo "  worktree:  $wt_dir"
  echo "  branch:    $branch  (off $base)"
  echo "  build dir: $target_dir"
  echo "  postgres:  $msg_pg"
  echo "  local docs: tasks/ design/ CLAUDE.md (symlinked from the main clone)"
  echo
  echo "next:"
  echo "  cd $wt_dir"
  echo "  cargo test                 # pure-core, isolated build dir"
  echo "  scripts/pgx.sh test pg$PG_MAJOR   # pgrx tests, isolated Postgres"
}

cmd_ls() {
  echo "Active worktrees:"
  git worktree list
  echo
  echo "Task branches + isolated Postgres ports (last commit age; flagged if no worktree):"
  local b slug home prun ptest age wt base_dir flag
  base_dir="$(dirname "$(main_worktree)")"
  while read -r b; do
    slug="${b#task/}"
    home="$HOME/.pgrx-$slug"
    age=$(git log -1 --format='%cr' "$b" 2>/dev/null || echo '?')
    wt="$base_dir/brindle-wt/$slug"
    flag=""; [[ -d "$wt" ]] || flag="  ⚠ no worktree (stale?)"
    if [[ -f "$home/config.toml" ]]; then
      prun=$(( $(sed -n 's/^base_port *= *//p' "$home/config.toml") + PG_MAJOR ))
      ptest=$(( $(sed -n 's/^base_testing_port *= *//p' "$home/config.toml") + PG_MAJOR ))
      printf '  %-28s run :%s  test :%s   %s%s\n' "$b" "$prun" "$ptest" "$age" "$flag"
    else
      printf '  %-28s (shared Postgres)   %s%s\n' "$b" "$age" "$flag"
    fi
  done < <(git for-each-ref --format='%(refname:short)' refs/heads/task/)
}

cmd_rm() {
  local slug="${1:-}"
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"
  local branch="task/$slug" base_dir wt_dir pgrx_home cache_dir
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/brindle-wt/$slug"
  pgrx_home="$HOME/.pgrx-$slug"
  cache_dir="$HOME/.cargo-target/$slug"

  if [[ -d "$pgrx_home" ]]; then
    PGRX_HOME="$pgrx_home" cargo pgrx stop "pg$PG_MAJOR" >/dev/null 2>&1 || true
    rm -rf "$pgrx_home"
    echo "removed isolated Postgres: $pgrx_home"
  fi

  if [[ -d "$cache_dir" ]]; then
    rm -rf "$cache_dir"
    echo "removed build cache: $cache_dir"
  fi

  if [[ -d "$wt_dir" ]]; then
    # Drop the doc symlinks first so they neither block removal nor get followed.
    find "$wt_dir" -maxdepth 1 -type l -delete 2>/dev/null || true
    git worktree remove "$wt_dir" \
      || die "worktree has uncommitted changes; commit/push or: git worktree remove --force '$wt_dir'"
    echo "removed worktree: $wt_dir"
  else
    git worktree prune
  fi

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    if git branch -d "$branch" 2>/dev/null; then
      echo "deleted branch:   $branch"
    elif branch_merged_via_pr "$branch"; then
      # Squash/rebase-merged: the work is on main even though `git branch -d` can't tell.
      git branch -D "$branch"
      echo "deleted branch:   $branch  (squash/rebase-merged via PR)"
    else
      die "branch $branch isn't merged (no merged PR found); if intentional: git branch -D '$branch'"
    fi
  fi
}

# Safety net, not the primary cleanup path: `rm` already deletes a task's
# pgrx home and build cache itself. This catches the two only if a worktree
# was torn down by bypassing the script (e.g. `git worktree remove` or
# `git branch -D` run by hand) instead of via `rm`, leaving them orphaned.
# Sweeps ~/.cargo-target/<slug> and ~/.pgrx-<slug> that have no live worktree
# or task/<slug> branch.
cmd_gc() {
  local dry_run=0
  [[ "${1:-}" == "--dry-run" ]] && dry_run=1

  local main_wt base_dir; main_wt="$(main_worktree)"; base_dir="$(dirname "$main_wt")"
  local cache_dir slug wt_dir age total_kb freed_kb=0 removed=0 kept=0

  for cache_dir in "$HOME"/.cargo-target/*/ "$HOME"/.pgrx-*/; do
    [[ -d "$cache_dir" ]] || continue
    slug="$(basename "$cache_dir")"
    [[ "$cache_dir" == "$HOME/.pgrx-"* ]] && slug="${slug#.pgrx-}"
    wt_dir="$base_dir/brindle-wt/$slug"

    if [[ -d "$wt_dir" ]] || git -C "$main_wt" show-ref --verify --quiet "refs/heads/task/$slug"; then
      kept=$((kept + 1))
      continue
    fi

    # Grace period: `new` creates these dirs before the branch/worktree exist,
    # so skip anything touched in the last hour to avoid a race with it.
    age=$(( $(date +%s) - $(stat -c %Y "$cache_dir") ))
    if [[ $age -lt 3600 ]]; then
      kept=$((kept + 1))
      continue
    fi

    total_kb=$(du -sk "$cache_dir" 2>/dev/null | cut -f1)
    freed_kb=$((freed_kb + total_kb))
    removed=$((removed + 1))
    if [[ $dry_run -eq 1 ]]; then
      echo "would remove: $cache_dir  (${total_kb} KB, no branch/worktree for '$slug')"
    else
      rm -rf "$cache_dir"
      echo "removed: $cache_dir  (${total_kb} KB, no branch/worktree for '$slug')"
    fi
  done

  echo
  if [[ $dry_run -eq 1 ]]; then
    echo "gc --dry-run: $removed orphaned dir(s), $((freed_kb / 1024)) MB would be freed; $kept kept"
  else
    echo "gc: $removed orphaned dir(s) removed, $((freed_kb / 1024)) MB freed; $kept kept"
  fi
}

[[ $# -ge 1 ]] || usage 1
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"

sub="$1"; shift
case "$sub" in
  new) cmd_new "$@" ;;
  ls|list) cmd_ls "$@" ;;
  rm|remove) cmd_rm "$@" ;;
  gc) cmd_gc "$@" ;;
  -h|--help|help) usage 0 ;;
  *) die "unknown command '$sub' (try: new | ls | rm | gc)" ;;
esac
