#!/usr/bin/env bash
#
# Per-task isolated sandboxes for parallel development.
#
# Each task gets its own git worktree (separate directory + branch) plus an
# isolated Cargo build directory, so several branches can be built and tested at
# the same time without clobbering one another's files or build output.
#
# Usage:
#   scripts/worktree.sh new <slug> [--pg-port N]   create branch task/<slug> + worktree
#   scripts/worktree.sh ls                          list active task worktrees
#   scripts/worktree.sh rm  <slug>                  remove the worktree + delete its branch
#
# Run from anywhere inside the main clone. Worktrees are created as siblings of the
# main clone under <parent>/brindle-wt/<slug>, on the Linux-native filesystem.
#
# See docs/DEVELOPMENT.md § "Parallel development with git worktrees".

set -euo pipefail

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
  sed -n '3,17p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

# Anchor everything on the *main* worktree (first entry of `git worktree list`),
# so the commands behave the same whether run from the main clone or a worktree.
main_worktree() {
  git worktree list --porcelain | sed -n 's/^worktree //p' | head -1
}

valid_slug() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || die "invalid slug '$1' (use letters, digits, . _ -)"
}

cmd_new() {
  local slug="" pg_port=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --pg-port) pg_port="${2:-}"; shift 2 || die "--pg-port needs a number" ;;
      --pg-port=*) pg_port="${1#*=}"; shift ;;
      -*) die "unknown option '$1'" ;;
      *) [[ -z "$slug" ]] && slug="$1" || die "unexpected argument '$1'"; shift ;;
    esac
  done
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"
  [[ -z "$pg_port" || "$pg_port" =~ ^[0-9]+$ ]] || die "--pg-port must be a number"

  local branch="task/$slug"
  local base_dir wt_dir target_dir
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/brindle-wt/$slug"
  target_dir="$HOME/.cargo-target/$slug"

  git show-ref --verify --quiet "refs/heads/$branch" && die "branch $branch already exists"
  [[ -e "$wt_dir" ]] && die "$wt_dir already exists"

  # Base the new branch on the freshest main we can reach (offline-safe).
  git fetch --quiet origin 2>/dev/null || echo "note: could not fetch origin; basing on local main"
  local base="main"
  git show-ref --verify --quiet refs/remotes/origin/main && base="origin/main"

  git worktree add -b "$branch" "$wt_dir" "$base"
  mkdir -p "$target_dir" "$wt_dir/.cargo"

  {
    echo "# Auto-generated by scripts/worktree.sh — isolates this worktree's build."
    echo "# Not committed (.cargo/ is git-ignored); safe to delete with the worktree."
    echo "[build]"
    echo "target-dir = \"$target_dir\""
    if [[ -n "$pg_port" ]]; then
      echo
      echo "[env]"
      echo "PGRX_HOME = \"$HOME/.pgrx-$slug\""
    fi
  } > "$wt_dir/.cargo/config.toml"

  echo
  echo "created worktree:  $wt_dir"
  echo "        branch:    $branch  (off $base)"
  echo "        build dir: $target_dir"
  if [[ -n "$pg_port" ]]; then
    echo
    echo "isolated Postgres requested. Initialize it once (downloads/builds pg17):"
    echo "  PGRX_HOME=$HOME/.pgrx-$slug cargo pgrx init"
    echo "then set its port to $pg_port in:  $HOME/.pgrx-$slug/config.toml"
  fi
  echo
  echo "next:  cd $wt_dir   (open your editor/session here; cargo auto-isolates)"
}

cmd_ls() {
  echo "Active worktrees:"
  git worktree list
  echo
  echo "Task branches:"
  git for-each-ref --format='  %(refname:short)' refs/heads/task/ || true
}

cmd_rm() {
  local slug="${1:-}"
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"
  local branch="task/$slug"
  local base_dir wt_dir
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/brindle-wt/$slug"

  if [[ -d "$wt_dir" ]]; then
    git worktree remove "$wt_dir" \
      || die "worktree has uncommitted changes; commit/push or rerun with: git worktree remove --force '$wt_dir'"
    echo "removed worktree: $wt_dir"
  else
    echo "note: $wt_dir not found (already removed?)"
    git worktree prune
  fi

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    git branch -d "$branch" \
      || die "branch $branch not fully merged; if intentional: git branch -D '$branch'"
    echo "deleted branch:   $branch"
  fi
  echo "(build cache at \$HOME/.cargo-target/$slug left in place — rm -rf it to reclaim disk)"
}

[[ $# -ge 1 ]] || usage 1
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"

sub="$1"; shift
case "$sub" in
  new) cmd_new "$@" ;;
  ls|list) cmd_ls "$@" ;;
  rm|remove) cmd_rm "$@" ;;
  -h|--help|help) usage 0 ;;
  *) die "unknown command '$sub' (try: new | ls | rm)" ;;
esac
